version: '2'

services:
  anaglyph:
    build: .
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - /mnt/data/robin_grun/:/workspace
    ports:
      - "8888:8888"
    restart: no
