services:
  anaglyph:
    build: .
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - /mnt/data/robin_grun/:/workspace
    ports:
      - "8888:8888"
    restart: no
    command: > 
      /bin/bash -c "cd /workspace/copy/anaglyph_computing/conditional_INNs/colorization_cINN && python setup.py build_ext --inplace && cd /workspace/anaglyph_computing/ && jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''"